### ISSUE TITLE
Uploading multiple images in one action

### ISSUE THREAD

**Issue by bwrsandman** [McCzarny/upload-image#2]
Could this action be modified to upload a list of images and have outputs be a list as well?

i.e.
```yml
      - uses: McCzarny/upload-image@v1.0.0
        id: upload-imgbb
        with:
          paths: |
              screenshot-1.png
              screenshot-2.png
              screenshot-3.png
              screenshot-4.png
          uploadMethod: imgbb
      - run: echo ${{steps.upload-imbb.outputs[3].url}}
```
